### ISSUE TITLE
Code review: 

### ISSUE THREAD

**Issue by melaniesigrid** [carloshs1994/To-Do-List#7]
Congratulations on building an amazing app! I love your implementation, and it looks like your code is DRY. There are a couple changes I suggest:

- You can add functionality so the trach icon returns to the kebab menu.
- If you want to make your project exactly like the video, you can make your items editable only on kebab menu click.
- The drag and drop function is quite complex, you could break it down into smaller functions and it could help the readability.
Cheers, and happy coding! You've done an AMAZING job.

<img src="https://media1.giphy.com/media/OyYK79ZIfWfCM/giphy.gif"/>

**Comment by carloshs1994** [comment]
<img src="https://media1.giphy.com/media/NEvPzZ8bd1V4Y/giphy.gif"/>
